// Login Page
export const ACTIVITY_DETAILS = "ACTIVITY_DETAILS";
export const ACTIVITY_FAVORITE = "ACTIVITY_FAVORITE";
export const CREATE_ACTIVITY_COMMENT = "CREATE_ACTIVITY_COMMENT";
export const CREATE_ACTIVITY = "CREATE_ACTIVITY";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
export const GET_ACTIVITY = "GET_ACTIVITY";
export const GET_ACTIVITY_COMMENTS = "GET_ACTIVITY_COMMENTS";
export const GET_LINK_PREVIEW = "GET_LINK_PREVIEW";
export const UPDATE_ACTIVITY = "UPDATE_ACTIVITY";

export const LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL";

export const MEMBER_AVATAR = "MEMBER_AVATAR";
export const MEMBER_COVER = "MEMBER_COVER";
export const MEMBER_PROFILE = "MEMBER_PROFILE";
export const ALL_MEMBERS_DETAILS = "ALL_MEMBERS_DETAILS";
export const MEMBER_DETAIL = "MEMBER_DETAIL";
export const ALL_MEMBERS = "ALL_MEMBERS";
export const DELETE_MEMBER = "DELETE_MEMBER";
export const MEMBER_ACTION = "MEMBER_ACTION";
